[workspace]
resolver = "2"
members = [
    "daemon",
    "check",
    "ctl",
    "crates/config",
    "crates/core",
    "crates/installer",
    "crates/fan",
    "crates/system",
    "crates/power",
    "crates/rgb",
    "crates/overclock",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
