[package]
name = "pyren-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pyren-core = { path = "../crates/core" }
pyren-fan = { path = "../crates/fan" }
pyren-system = { path = "../crates/system" }
pyren-power = { path = "../crates/power" }
pyren-installer = { path = "../crates/installer" }
