PACKAGE_NAME="@PKGNAME@"
PACKAGE_VERSION="@PKGVER@"
MAKE[0]="env -u KERNELRELEASE make -C src/hp-wmi-omen KVERSION=${kernelver}"
CLEAN="make -C src/hp-wmi-omen clean"
BUILT_MODULE_NAME[0]="hp-wmi"
BUILT_MODULE_LOCATION[0]="src/hp-wmi-omen/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86/hp"
AUTOINSTALL="yes"
